-- CreateTable
CREATE TABLE "notification_preferences" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "pushEnabled" BOOLEAN NOT NULL DEFAULT true,
    "newFriendEvents" BOOLEAN NOT NULL DEFAULT true,
    "eventReminders" BOOLEAN NOT NULL DEFAULT true,
    "eventUpdates" BOOLEAN NOT NULL DEFAULT true,
    "eventCancellations" BOOLEAN NOT NULL DEFAULT true,
    "eventStartingSoon" BOOLEAN NOT NULL DEFAULT true,
    "newAttendee" BOOLEAN NOT NULL DEFAULT true,
    "attendeeDeclined" BOOLEAN NOT NULL DEFAULT true,
    "someoneInterested" BOOLEAN NOT NULL DEFAULT true,
    "rsvpReminders" BOOLEAN NOT NULL DEFAULT true,
    "eventRequestInvites" BOOLEAN NOT NULL DEFAULT true,
    "eventRequestResponses" BOOLEAN NOT NULL DEFAULT true,
    "eventRequestConfirmed" BOOLEAN NOT NULL DEFAULT true,
    "eventRequestNudges" BOOLEAN NOT NULL DEFAULT true,
    "eventComments" BOOLEAN NOT NULL DEFAULT true,
    "eventPhotos" BOOLEAN NOT NULL DEFAULT true,
    "commentReplies" BOOLEAN NOT NULL DEFAULT true,
    "friendRequests" BOOLEAN NOT NULL DEFAULT true,
    "friendRequestAccepted" BOOLEAN NOT NULL DEFAULT true,
    "friendBirthdays" BOOLEAN NOT NULL DEFAULT true,
    "circleMessages" BOOLEAN NOT NULL DEFAULT true,
    "circleEvents" BOOLEAN NOT NULL DEFAULT true,
    "circleInvites" BOOLEAN NOT NULL DEFAULT true,
    "fomoFriendJoined" BOOLEAN NOT NULL DEFAULT true,
    "fomoPopularEvents" BOOLEAN NOT NULL DEFAULT true,
    "weeklySummary" BOOLEAN NOT NULL DEFAULT true,
    "reconnectSuggestions" BOOLEAN NOT NULL DEFAULT true,
    "businessEvents" BOOLEAN NOT NULL DEFAULT true,
    "dailyDigest" BOOLEAN NOT NULL DEFAULT false,
    "dailyDigestTime" TEXT NOT NULL DEFAULT '09:00',
    "quietHoursEnabled" BOOLEAN NOT NULL DEFAULT false,
    "quietHoursStart" TEXT NOT NULL DEFAULT '22:00',
    "quietHoursEnd" TEXT NOT NULL DEFAULT '08:00',
    "eventReflectionPrompts" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "notification_preferences_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "notification_preferences_userId_key" ON "notification_preferences"("userId");
